name: Build and deploy to server

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Create docker image and push to registry, then start image
    runs-on: ubuntu-latest
    steps:
    - uses: de-vri-es/setup-git-credentials@v2
      with: 
        credentials: https://erfrost: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@github.com/
      
    - name: Pull image and run container with .env variables from secrets
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 31.184.254.214
        username: root
        password: 1awj3vkosi
        port: 22
        script: cd /root/client && git pull origin master && ( docker stop client || true ) && (docker rm client || true) && (docker build -t client . || true) && docker run -d -p 81:80 --name client --restart always client && docker image prune --filter="dangling=true" -f
